import { type LangCode } from "@/hooks/useLanguage";

/**
 * Bloc/module title translations keyed by the Catalan name (bloc.nom).
 * If a translation is missing for the requested helpLang, falls back to
 * English, then to the original Catalan.
 */
const blocNames: Record<string, Partial<Record<LangCode, string>>> = {
  "Salutacions": { es: "Saludos", en: "Greetings", fr: "Salutations", ar: "التحيات", ur: "سلام", pt: "Saudações", ptBR: "Saudações", it: "Saluti", ro: "Salutări", uk: "Привітання", el: "Χαιρετισμοί", zh: "问候语", hi: "अभिवादन", wo: "Nuyu", mnk: "Kontondiroo", ha: "السلام", snk: "Salaame", srk: "Salaame" },
  "Animals": { es: "Animales", en: "Animals", fr: "Animaux", ar: "الحيوانات", ur: "جانور", pt: "Animais", ptBR: "Animais", it: "Animali", ro: "Animale", uk: "Тварини", el: "Ζώα", zh: "动物", hi: "जानवर", wo: "Mala yi", mnk: "Daafeŋolu", ha: "الحيوانات", snk: "Tinmu", srk: "Tinmu" },
  "L'Aula": { es: "El Aula", en: "The Classroom", fr: "La Salle de classe", ar: "الفصل", ur: "کلاس روم", pt: "A Sala de Aula", ptBR: "A Sala de Aula", it: "L'Aula", ro: "Sala de clasă", uk: "Клас", el: "Η Τάξη", zh: "教室", hi: "कक्षा", wo: "Kalaas bi", mnk: "Karaŋ bunoo", ha: "القسم", snk: "Karaŋ buŋe", srk: "Karaŋ buŋe" },
  "Colors": { es: "Colores", en: "Colors", fr: "Couleurs", ar: "الألوان", ur: "رنگ", pt: "Cores", ptBR: "Cores", it: "Colori", ro: "Culori", uk: "Кольори", el: "Χρώματα", zh: "颜色", hi: "रंग", wo: "Kulër yi", mnk: "Kuleroolu", ha: "الألوان", snk: "Kuleri", srk: "Kuleri" },
  "Números": { es: "Números", en: "Numbers", fr: "Nombres", ar: "الأرقام", ur: "اعداد", pt: "Números", ptBR: "Números", it: "Numeri", ro: "Numere", uk: "Числа", el: "Αριθμοί", zh: "数字", hi: "संख्या", wo: "Limu yi", mnk: "Yaatewolu", ha: "الأرقام", snk: "Limmu", srk: "Limmu" },
  "La Família": { es: "La Familia", en: "The Family", fr: "La Famille", ar: "العائلة", ur: "خاندان", pt: "A Família", ptBR: "A Família", it: "La Famiglia", ro: "Familia", uk: "Сім'я", el: "Η Οικογένεια", zh: "家庭", hi: "परिवार", wo: "Njaboot gi", mnk: "Dimbaayaa", ha: "العائلة", snk: "Dembayaaxu", srk: "Dembayaaxu" },
  "El Cos Humà": { es: "El Cuerpo Humano", en: "The Human Body", fr: "Le Corps Humain", ar: "جسم الإنسان", ur: "انسانی جسم", pt: "O Corpo Humano", ptBR: "O Corpo Humano", it: "Il Corpo Umano", ro: "Corpul Uman", uk: "Тіло людини", el: "Το Ανθρώπινο Σώμα", zh: "人体", hi: "मानव शरीर", wo: "Yaramu nit", mnk: "Hadamadiŋ baloo", ha: "جسم الإنسان", snk: "Adamaxe yintaxu", srk: "Adamaxe yintaxu" },
  "El Menjar": { es: "La Comida", en: "Food", fr: "La Nourriture", ar: "الطعام", ur: "کھانا", pt: "A Comida", ptBR: "A Comida", it: "Il Cibo", ro: "Mâncarea", uk: "Їжа", el: "Το Φαγητό", zh: "食物", hi: "भोजन", wo: "Lekk gi", mnk: "Domoroo", ha: "الماكلة", snk: "Yiganne", srk: "Yiganne" },
  "Emocions": { es: "Emociones", en: "Emotions", fr: "Émotions", ar: "المشاعر", ur: "جذبات", pt: "Emoções", ptBR: "Emoções", it: "Emozioni", ro: "Emoții", uk: "Емоції", el: "Συναισθήματα", zh: "情绪", hi: "भावनाएँ", wo: "Yëgu yi", mnk: "Sondomeŋo kuwolu", ha: "الإحساس", snk: "Sondomexu", srk: "Sondomexu" },
  "Dies i Mesos": { es: "Días y Meses", en: "Days and Months", fr: "Jours et Mois", ar: "الأيام والأشهر", ur: "دن اور مہینے", pt: "Dias e Meses", ptBR: "Dias e Meses", it: "Giorni e Mesi", ro: "Zile și Luni", uk: "Дні і місяці", el: "Ημέρες και Μήνες", zh: "日和月", hi: "दिन और महीने", wo: "Bés ak weer", mnk: "Tilolu niŋ karoolu", ha: "النهار والشهور", snk: "Xole nun karo", srk: "Xole nun karo" },
  "La Casa": { es: "La Casa", en: "The House", fr: "La Maison", ar: "البيت", ur: "گھر", pt: "A Casa", ptBR: "A Casa", it: "La Casa", ro: "Casa", uk: "Дім", el: "Το Σπίτι", zh: "家", hi: "घर", wo: "Kër gi", mnk: "Buŋo", ha: "الدار", snk: "Kaaŋe", srk: "Kaaŋe" },
  "La Roba": { es: "La Ropa", en: "Clothes", fr: "Les Vêtements", ar: "الملابس", ur: "کپڑے", pt: "A Roupa", ptBR: "A Roupa", it: "I Vestiti", ro: "Hainele", uk: "Одяг", el: "Τα Ρούχα", zh: "衣服", hi: "कपड़े", wo: "Yére yi", mnk: "Duŋfaanu", ha: "الحوايج", snk: "Yaxara", srk: "Yaxara" },
  "Presenta't": { es: "Preséntate", en: "Introduce Yourself", fr: "Présente-toi", ar: "قدم نفسك", ur: "اپنا تعارف کرائیں", pt: "Apresenta-te", ptBR: "Apresente-se", it: "Presentati", ro: "Prezintă-te", uk: "Представся", el: "Συστήσου", zh: "自我介绍", hi: "अपना परिचय दें", wo: "Xamle sa bopp", mnk: "I faŋo yitandi", ha: "قدّم راسك", snk: "I yinme yittindi", srk: "I yinme yittindi" },
  "Descriu la Cristina": { es: "Describe a Cristina", en: "Describe Cristina", fr: "Décris Cristina", ar: "صف كريستينا", ur: "کرسٹینا کا تعارف", pt: "Descreve a Cristina", ptBR: "Descreva a Cristina", it: "Descrivi Cristina", ro: "Descrie-o pe Cristina", uk: "Опиши Крістіну", el: "Περίγραψε την Κριστίνα", zh: "描述克里斯蒂娜", hi: "क्रिस्टीना का वर्णन", wo: "Misaal Cristina", mnk: "Cristina yaabi", ha: "وصف كريستينا", snk: "Cristina ŋaake", srk: "Cristina ŋaake" },
  "El Mercat": { es: "El Mercado", en: "The Market", fr: "Le Marché", ar: "السوق", ur: "بازار", pt: "O Mercado", ptBR: "O Mercado", it: "Il Mercato", ro: "Piața", uk: "Ринок", el: "Η Αγορά", zh: "市场", hi: "बाज़ार", wo: "Marse bi", mnk: "Marisewo", ha: "السوق", snk: "Maraase", srk: "Maraase" },
  "El Gimnàs": { es: "El Gimnasio", en: "The Gym", fr: "Le Gymnase", ar: "صالة الرياضة", ur: "جم", pt: "O Ginásio", ptBR: "A Academia", it: "La Palestra", ro: "Sala de sport", uk: "Спортзал", el: "Το Γυμναστήριο", zh: "健身房", hi: "जिम", wo: "Sport bi", mnk: "Sportoo", ha: "السبور", snk: "Sportexu", srk: "Sportexu" },
  "Ocells": { es: "Pájaros", en: "Birds", fr: "Oiseaux", ar: "الطيور", ur: "پرندے", pt: "Pássaros", ptBR: "Pássaros", it: "Uccelli", ro: "Păsări", uk: "Птахи", el: "Πουλιά", zh: "鸟类", hi: "पक्षी", wo: "Pikc yi", mnk: "Konolu", ha: "الطيور", snk: "Konnu", srk: "Konnu" },
  "Transport": { es: "Transporte", en: "Transport", fr: "Transport", ar: "المواصلات", ur: "ٹرانسپورٹ", pt: "Transporte", ptBR: "Transporte", it: "Trasporto", ro: "Transport", uk: "Транспорт", el: "Μεταφορά", zh: "交通", hi: "परिवहन", wo: "Yoonu mbalit", mnk: "Taamasiŋolu", ha: "النقل", snk: "Tamaye", srk: "Tamaye" },
  "La Natura": { es: "La Naturaleza", en: "Nature", fr: "La Nature", ar: "الطبيعة", ur: "قدرت", pt: "A Natureza", ptBR: "A Natureza", it: "La Natura", ro: "Natura", uk: "Природа", el: "Η Φύση", zh: "大自然", hi: "प्रकृति", wo: "Mboole bi", mnk: "Daafeŋ baŋo", ha: "الطبيعة", snk: "Daande", srk: "Daande" },
  "Jocs de Taula": { es: "Juegos de Mesa", en: "Board Games", fr: "Jeux de société", ar: "ألعاب الطاولة", ur: "بورڈ گیمز", pt: "Jogos de Mesa", ptBR: "Jogos de Tabuleiro", it: "Giochi da Tavolo", ro: "Jocuri de masă", uk: "Настільні ігри", el: "Επιτραπέζια Παιχνίδια", zh: "桌游", hi: "बोर्ड खेल", wo: "Po u taabal", mnk: "Taabuli tulonoolu", ha: "ألعاب الطابلة", snk: "Taabule wureyi", srk: "Taabule wureyi" },
  "El Temps": { es: "El Tiempo", en: "The Weather", fr: "Le Temps", ar: "الطقس", ur: "موسم", pt: "O Tempo", ptBR: "O Tempo", it: "Il Tempo", ro: "Vremea", uk: "Погода", el: "Ο Καιρός", zh: "天气", hi: "मौसम", wo: "Asaman bi", mnk: "Tilibo waatoo", ha: "الجو", snk: "Tilibo waati", srk: "Tilibo waati" },
  "La Ciutat": { es: "La Ciudad", en: "The City", fr: "La Ville", ar: "المدينة", ur: "شہر", pt: "A Cidade", ptBR: "A Cidade", it: "La Città", ro: "Orașul", uk: "Місто", el: "Η Πόλη", zh: "城市", hi: "शहर", wo: "Dëkk bi", mnk: "Saatewo", ha: "المدينة", snk: "Saare", srk: "Saare" },
  "Salut": { es: "Salud", en: "Health", fr: "Santé", ar: "الصحة", ur: "صحت", pt: "Saúde", ptBR: "Saúde", it: "Salute", ro: "Sănătate", uk: "Здоров'я", el: "Υγεία", zh: "健康", hi: "स्वास्थ्य", wo: "Wér-gi-yaram", mnk: "Kendeyaa", ha: "الصحة", snk: "Senne", srk: "Senne" },
  "Hobbis i Temps Lliure": { es: "Aficiones y Tiempo Libre", en: "Hobbies and Free Time", fr: "Loisirs et Temps Libre", ar: "الهوايات ووقت الفراغ", ur: "مشاغل اور فارغ وقت", pt: "Passatempos e Tempo Livre", ptBR: "Hobbies e Tempo Livre", it: "Hobby e Tempo Libero", ro: "Hobby-uri și Timp Liber", uk: "Хобі та вільний час", el: "Χόμπι και Ελεύθερος Χρόνος", zh: "爱好与休闲", hi: "शौक और खाली समय", wo: "Bëgg-bëgg ak xew", mnk: "Yiriwaalu niŋ kewolu", ha: "هوايات والوقت الحر", snk: "Kewolu nun waati", srk: "Kewolu nun waati" },
  "El Restaurant": { es: "El Restaurante", en: "The Restaurant", fr: "Le Restaurant", ar: "المطعم", ur: "ریستوران", pt: "O Restaurante", ptBR: "O Restaurante", it: "Il Ristorante", ro: "Restaurantul", uk: "Ресторан", el: "Το Εστιατόριο", zh: "餐厅", hi: "रेस्तरां", wo: "Restoraan bi", mnk: "Restoraanoo", ha: "الريستورا", snk: "Restoraane", srk: "Restoraane" },
  "Les Vacances": { es: "Las Vacaciones", en: "Holidays", fr: "Les Vacances", ar: "العطلة", ur: "چھٹیاں", pt: "As Férias", ptBR: "As Férias", it: "Le Vacanze", ro: "Vacanțele", uk: "Канікули", el: "Οι Διακοπές", zh: "假期", hi: "छुट्टियाँ", wo: "Bëccëgu noflaay", mnk: "Dahaa waatoolu", ha: "العطلة", snk: "Dahaa", srk: "Dahaa" },
  "Tecnologia Bàsica": { es: "Tecnología Básica", en: "Basic Technology", fr: "Technologie de base", ar: "التكنولوجيا الأساسية", ur: "بنیادی ٹیکنالوجی", pt: "Tecnologia Básica", ptBR: "Tecnologia Básica", it: "Tecnologia Base", ro: "Tehnologie de bază", uk: "Базова технологія", el: "Βασική Τεχνολογία", zh: "基础技术", hi: "बुनियादी तकनीक", wo: "Teknolojii bu tane", mnk: "Teknolojii foloo", ha: "التكنولوجيا الأساسية", snk: "Teknolojii folle", srk: "Teknolojii folle" },
  "Les Professions": { es: "Las Profesiones", en: "Professions", fr: "Les Métiers", ar: "المهن", ur: "پیشے", pt: "As Profissões", ptBR: "As Profissões", it: "Le Professioni", ro: "Profesiile", uk: "Професії", el: "Τα Επαγγέλματα", zh: "职业", hi: "व्यवसाय", wo: "Liggéey yi", mnk: "Dookuwolu", ha: "المهن", snk: "Goloyaaxu", srk: "Goloyaaxu" },
  "Eines de Fusta": { es: "Herramientas de Madera", en: "Wood Tools", fr: "Outils en bois", ar: "أدوات الخشب", ur: "لکڑی کے اوزار", pt: "Ferramentas de Madeira", ptBR: "Ferramentas de Madeira", it: "Strumenti in Legno", ro: "Unelte de lemn", uk: "Дерев'яні інструменти", el: "Εργαλεία Ξύλου", zh: "木工工具", hi: "लकड़ी के औज़ार", wo: "Jumtukaay u garab", mnk: "Yiri dookuraŋolu", ha: "أدوات العود", snk: "Yiri jaŋŋe", srk: "Yiri jaŋŋe" },
  "Eines de Dibuix": { es: "Herramientas de Dibujo", en: "Drawing Tools", fr: "Outils de Dessin", ar: "أدوات الرسم", ur: "ڈرائنگ کے اوزار", pt: "Ferramentas de Desenho", ptBR: "Ferramentas de Desenho", it: "Strumenti da Disegno", ro: "Unelte de desen", uk: "Інструменти для малювання", el: "Εργαλεία Σχεδίου", zh: "绘图工具", hi: "चित्रकला उपकरण", wo: "Jumtukaay u nataal", mnk: "Nataloo dookuraŋolu", ha: "أدوات الرسم", snk: "Nataloo jaŋŋe", srk: "Nataloo jaŋŋe" },
  "Eines de Percussió": { es: "Instrumentos de Percusión", en: "Percussion Instruments", fr: "Instruments à Percussion", ar: "آلات الإيقاع", ur: "تال آلات", pt: "Instrumentos de Percussão", ptBR: "Instrumentos de Percussão", it: "Strumenti a Percussione", ro: "Instrumente de percuție", uk: "Перкусійні інструменти", el: "Κρουστά", zh: "打击乐器", hi: "ताल वाद्य", wo: "Jumtukaay u sabar", mnk: "Tantaŋolu", ha: "آلات الإيقاع", snk: "Tantaŋolu", srk: "Tantaŋolu" },
  "L'Aula (avançat)": { es: "El Aula (avanzado)", en: "The Classroom (advanced)", fr: "La Salle de classe (avancé)", ar: "الفصل (متقدم)", ur: "کلاس (اعلیٰ)", pt: "A Sala de Aula (avançado)", ptBR: "A Sala de Aula (avançado)", it: "L'Aula (avanzato)", ro: "Sala de clasă (avansat)", uk: "Клас (просунутий)", el: "Η Τάξη (προχωρημένο)", zh: "教室（高级）", hi: "कक्षा (उन्नत)", wo: "Kalaas bi (kawe)", mnk: "Karaŋ bunoo (santo)", ha: "القسم (متقدم)", snk: "Karaŋ buŋe (santo)", srk: "Karaŋ buŋe (santo)" },
  "Mobiliari de la Casa": { es: "Muebles de la Casa", en: "Home Furniture", fr: "Mobilier de la Maison", ar: "أثاث المنزل", ur: "گھر کا فرنیچر", pt: "Mobília da Casa", ptBR: "Móveis da Casa", it: "Arredamento della Casa", ro: "Mobilier de casă", uk: "Меблі для дому", el: "Έπιπλα Σπιτιού", zh: "家具", hi: "घर का फर्नीचर", wo: "Pertu kër", mnk: "Buŋ jooraŋolu", ha: "أثاث الدار", snk: "Kaa jaŋŋe", srk: "Kaa jaŋŋe" },
  "Presenta la teva família": { es: "Presenta a tu familia", en: "Introduce Your Family", fr: "Présente ta famille", ar: "قدّم عائلتك", ur: "اپنے خاندان کا تعارف", pt: "Apresenta a tua família", ptBR: "Apresente sua família", it: "Presenta la tua famiglia", ro: "Prezintă-ți familia", uk: "Представ свою сім'ю", el: "Σύστησε την οικογένειά σου", zh: "介绍你的家人", hi: "अपने परिवार का परिचय दें", wo: "Xamle sa njaboot", mnk: "I la dimbaayaa yitandi", ha: "قدّم عائلتك", snk: "I dembayaaxu yittindi", srk: "I dembayaaxu yittindi" },
  "Explica la teva rutina": { es: "Explica tu rutina", en: "Describe Your Routine", fr: "Décris ta routine", ar: "اشرح روتينك", ur: "اپنا معمول بیان کریں", pt: "Explica a tua rotina", ptBR: "Explique sua rotina", it: "Racconta la tua routine", ro: "Explică-ți rutina", uk: "Розкажи про свій розпорядок", el: "Εξήγησε τη ρουτίνα σου", zh: "讲述你的日常", hi: "अपनी दिनचर्या बताएं", wo: "Wax sa jëf yu bés bu nekk", mnk: "I la luŋ-luŋ kuwolu fo", ha: "حكي روتينك", snk: "I xole xolexu sefene", srk: "I xole xolexu sefene" },
  "Donar Opinions": { es: "Dar Opiniones", en: "Giving Opinions", fr: "Donner son avis", ar: "إبداء الرأي", ur: "رائے دینا", pt: "Dar Opiniões", ptBR: "Dar Opiniões", it: "Dare Opinioni", ro: "A oferi opinii", uk: "Висловлювати думки", el: "Δίνοντας Γνώμες", zh: "发表意见", hi: "राय देना", wo: "Joxe sa xalaat", mnk: "Miiroolu dii", ha: "تعطي الرأي", snk: "Miiri sefene", srk: "Miiri sefene" },
  "Medi Ambient": { es: "Medio Ambiente", en: "Environment", fr: "Environnement", ar: "البيئة", ur: "ماحول", pt: "Meio Ambiente", ptBR: "Meio Ambiente", it: "Ambiente", ro: "Mediul înconjurător", uk: "Довкілля", el: "Περιβάλλον", zh: "环境", hi: "पर्यावरण", wo: "Mboole bi", mnk: "Daakaa", ha: "البيئة", snk: "Daande", srk: "Daande" },
  "Cultura Catalana": { es: "Cultura Catalana", en: "Catalan Culture", fr: "Culture Catalane", ar: "الثقافة الكاتالانية", ur: "کاتالان ثقافت", pt: "Cultura Catalã", ptBR: "Cultura Catalã", it: "Cultura Catalana", ro: "Cultura Catalană", uk: "Каталонська культура", el: "Καταλανική Κουλτούρα", zh: "加泰罗尼亚文化", hi: "कातालान संस्कृति", wo: "Aada katalan", mnk: "Katalan aadoo", ha: "الثقافة الكاتالانية", snk: "Katalan aadaaxu", srk: "Katalan aadaaxu" },
  "Viatges": { es: "Viajes", en: "Travel", fr: "Voyages", ar: "السفر", ur: "سفر", pt: "Viagens", ptBR: "Viagens", it: "Viaggi", ro: "Călătorii", uk: "Подорожі", el: "Ταξίδια", zh: "旅行", hi: "यात्रा", wo: "Tukki yi", mnk: "Taamoolu", ha: "السفر", snk: "Taame", srk: "Taame" },
  "El Món Laboral": { es: "El Mundo Laboral", en: "The World of Work", fr: "Le Monde du Travail", ar: "عالم العمل", ur: "دنیائے کار", pt: "O Mundo do Trabalho", ptBR: "O Mundo do Trabalho", it: "Il Mondo del Lavoro", ro: "Lumea Muncii", uk: "Світ роботи", el: "Ο Κόσμος της Εργασίας", zh: "工作世界", hi: "कार्य जगत", wo: "Àdduna liggéey", mnk: "Dookuwo duniyaa", ha: "عالم الخدمة", snk: "Goloyaaxu duniya", srk: "Goloyaaxu duniya" },
  "Tecnologia": { es: "Tecnología", en: "Technology", fr: "Technologie", ar: "التكنولوجيا", ur: "ٹیکنالوجی", pt: "Tecnologia", ptBR: "Tecnologia", it: "Tecnologia", ro: "Tehnologie", uk: "Технології", el: "Τεχνολογία", zh: "技术", hi: "तकनीक", wo: "Teknolojii", mnk: "Teknolojii", ha: "التكنولوجيا", snk: "Teknolojii", srk: "Teknolojii" },
  "Sentiments i Relacions": { es: "Sentimientos y Relaciones", en: "Feelings and Relationships", fr: "Sentiments et Relations", ar: "المشاعر والعلاقات", ur: "احساسات اور رشتے", pt: "Sentimentos e Relações", ptBR: "Sentimentos e Relacionamentos", it: "Sentimenti e Relazioni", ro: "Sentimente și Relații", uk: "Почуття та стосунки", el: "Συναισθήματα και Σχέσεις", zh: "情感与关系", hi: "भावनाएँ और रिश्ते", wo: "Yëg ak jokkalante", mnk: "Sondomeŋo niŋ kafuyaa", ha: "الإحساس والعلاقات", snk: "Sondomexu nun jokke", srk: "Sondomexu nun jokke" },
  "Connectors del Discurs": { es: "Conectores del Discurso", en: "Discourse Connectors", fr: "Connecteurs du Discours", ar: "أدوات الربط", ur: "ربط الفاظ", pt: "Conectores do Discurso", ptBR: "Conectores do Discurso", it: "Connettori del Discorso", ro: "Conectori de discurs", uk: "Сполучники мовлення", el: "Συνδετικές Λέξεις", zh: "话语连接词", hi: "संयोजक शब्द", wo: "Xayli waxin", mnk: "Diyaamoo dendolu", ha: "أدوات الربط", snk: "Sefene jaaxe", srk: "Sefene jaaxe" },
  "Explica una experiència personal": { es: "Cuenta una experiencia personal", en: "Tell a Personal Experience", fr: "Raconte une expérience personnelle", ar: "احكِ تجربة شخصية", ur: "ذاتی تجربہ بیان کریں", pt: "Conta uma experiência pessoal", ptBR: "Conte uma experiência pessoal", it: "Racconta un'esperienza personale", ro: "Spune o experiență personală", uk: "Розкажи особистий досвід", el: "Διηγήσου μια προσωπική εμπειρία", zh: "讲述个人经历", hi: "एक व्यक्तिगत अनुभव बताएं", wo: "Nettali sa yaakaar", mnk: "I faŋo la jamfaa fo", ha: "حكي تجربتك", snk: "I yinme jamfa sefene", srk: "I yinme jamfa sefene" },
  "Dóna la teva opinió sobre un tema": { es: "Da tu opinión sobre un tema", en: "Give Your Opinion on a Topic", fr: "Donne ton avis sur un sujet", ar: "أعطِ رأيك في موضوع", ur: "کسی موضوع پر اپنی رائے دیں", pt: "Dá a tua opinião sobre um tema", ptBR: "Dê sua opinião sobre um tema", it: "Esprimi la tua opinione su un argomento", ro: "Dă-ți părerea despre un subiect", uk: "Висловіть думку про тему", el: "Δώσε τη γνώμη σου σε ένα θέμα", zh: "对一个话题发表意见", hi: "किसी विषय पर अपनी राय दें", wo: "Joxe sa xalaat ci benn topik", mnk: "I la miiroo dii kuu kaŋ", ha: "اعطي رأيك في موضوع", snk: "I miiri sefene kuu kanma", srk: "I miiri sefene kuu kanma" },
};

/**
 * Translate a Catalan bloc/module title into the help language.
 * Falls back to English, then to the original Catalan name.
 */
export function tBlocName(catalanName: string, helpLang: LangCode): string {
  if (helpLang === "ca") return catalanName;
  const entry = blocNames[catalanName];
  if (!entry) return catalanName;
  return entry[helpLang] ?? entry.en ?? catalanName;
}
